site_name: Web-ohjelmointi ja web-palvelinohjelmointi harjoitustyö
site_url: https://webdev-ht.nanjo.tech/documentation
repo_url: https://github.com/IamNanjo/webdev-ht
site_description: Tietokannat harjoitustyön dokumentaatio

theme:
  name: material
  palette:
    scheme: slate
    primary: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.top

site_dir: ../documentation
extra_css:
  - styles/smooth-scrolling.css